# Generated by Django 6.1.1 on 2026-10-02 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('send_email', 'Send email'), ('send_email_batch', 'Send email batch'), ('inbox_sync', 'Mailbox sync'), ('apollo_search', 'Apollo search'), ('hunter_search', 'Hunter search'), ('generate_draft', 'Generate draft'), ('draft_queue', 'Draft review queue'), ('followup_batch', 'Scheduled follow-ups')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='async_job_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_job_user_idempotency'), models.UniqueConstraint(condition=models.Q(('job_type__in', ('inbox_sync', 'followup_batch')), ('status__in', ('queued', 'running'))), fields=('user', 'job_type'), name='uniq_active_periodic_job_per_user')],
            },
        ),
    ]
