# Generated by Django 6.1.1 on 2026-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='dispatch_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='last_dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
