# Generated by Django 6.1.1 on 2026-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_jobs', '0002_backgroundjob_dispatch_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('send_email', 'Send email'), ('send_email_batch', 'Send email batch'), ('inbox_sync', 'Mailbox sync'), ('apollo_search', 'Apollo search'), ('hunter_search', 'Hunter search'), ('generate_draft', 'Generate draft'), ('draft_queue', 'Draft review queue'), ('followup_batch', 'Scheduled follow-ups'), ('classify_replies', 'Classify replies')], max_length=32),
        ),
    ]
