# Generated by Django 6.1.1 on 2026-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='auth_type',
            field=models.CharField(choices=[('smtp', 'Custom SMTP'), ('oauth_google', 'Google OAuth'), ('oauth_microsoft', 'Microsoft OAuth')], default='smtp', max_length=20),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='encrypted_access_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='encrypted_refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
    ]
