# Generated by Django 6.1.1 on 2026-09-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_emailaccount_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='encrypted_imap_password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_port',
            field=models.IntegerField(blank=True, default=993, null=True),
        ),
    ]
