# Generated by Django 6.1.1 on 2026-09-26 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_emailaccount_encrypted_imap_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('bounced', 'Hard Bounced'), ('complained', 'Spam Complaint'), ('manual', 'Manually Added')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'email'], name='integration_user_id_b485ff_idx'), models.Index(fields=['user', 'domain'], name='integration_user_id_31eb29_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'email'), name='uniq_suppression_email_per_user')],
            },
        ),
    ]
