# Generated by Django 6.1.1 on 2026-09-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='daily_send_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sends_counted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sends_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
