# Generated by Django 6.1.1 on 2026-09-26 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_emailaccount_daily_send_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apiintegration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apiintegration',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiintegration',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiintegration',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='apiintegration',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='uniq_integration_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='apiintegration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='uniq_primary_llm_per_user'),
        ),
    ]
