# Generated by Django 6.1.1 on 2026-09-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_oauthstate_browser_binding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegration',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('apollo', 'Apollo'), ('hunter', 'Hunter')], max_length=50),
        ),
    ]
