# Generated by Django 6.1.1 on 2026-10-02 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_suppressionentry_domain_uniqueness'),
        ('leads', '0008_lead_employee_count_lead_funding_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='active', max_length=12)),
                ('sent_follow_ups', models.PositiveSmallIntegerField(default=0)),
                ('next_send_at', models.DateTimeField(db_index=True)),
                ('last_sent_at', models.DateTimeField()),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('prepared_subject', models.CharField(blank=True, default='', max_length=255)),
                ('prepared_body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_sequence', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_send_at'], name='followup_due_idx')],
            },
        ),
    ]
