# Generated by Django 6.1.1 on 2026-10-05 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_followupsequence_paused'),
        ('leads', '0009_lead_email_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimize_send_time', models.BooleanField(default=False)),
                ('earliest_hour', models.PositiveSmallIntegerField(default=8)),
                ('latest_hour', models.PositiveSmallIntegerField(default=17)),
                ('weekdays_only', models.BooleanField(default=True)),
                ('fallback_timezone', models.CharField(default='UTC', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sending_window', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('recipient_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.emailaccount')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sends', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'send_at'], name='scheduledsend_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('user', 'lead'), name='uniq_active_scheduled_send_per_lead')],
            },
        ),
    ]
