# Generated by Django 6.1.1 on 2026-10-05 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_sendingwindow_scheduledsend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDeliverability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At risk'), ('failing', 'Failing'), ('error', 'Check failed')], default='error', max_length=12)),
                ('spf_status', models.CharField(default='unknown', max_length=12)),
                ('spf_record', models.TextField(blank=True, default='')),
                ('dkim_status', models.CharField(default='unknown', max_length=12)),
                ('dkim_selectors', models.JSONField(blank=True, default=list)),
                ('dmarc_status', models.CharField(default='unknown', max_length=12)),
                ('dmarc_policy', models.CharField(blank=True, default='', max_length=12)),
                ('dmarc_record', models.TextField(blank=True, default='')),
                ('issues', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('has_alert', models.BooleanField(default=False)),
                ('alert_message', models.TextField(blank=True, default='')),
                ('first_checked_at', models.DateTimeField(auto_now_add=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_deliverability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'has_alert'], name='integration_user_id_446334_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'domain'), name='uniq_domain_deliverability_per_user')],
            },
        ),
    ]
