"""
Django settings for richlead_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import unquote, urlsplit
from cryptography.fernet import Fernet
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')


def _required_secret(name, dev_factory):
    """Read a secret from the environment.

    Outside DEBUG the value is mandatory and startup fails without it, so a missing
    .env can never silently downgrade to a known-public key. In DEBUG a generated
    value is cached on disk (gitignored) so it survives autoreloads -- a key that
    changed each restart would make every stored credential undecryptable.
    """
    value = os.getenv(name)
    if value:
        return value
    if not DEBUG:
        raise ImproperlyConfigured(
            f"{name} must be set in the environment when DEBUG is off. "
            f"See backend/.env.example."
        )

    cache_file = BASE_DIR / '.dev-secrets' / name
    if cache_file.exists():
        return cache_file.read_text().strip()

    generated = dev_factory()
    cache_file.parent.mkdir(exist_ok=True)
    cache_file.write_text(generated)
    cache_file.chmod(0o600)
    return generated


SECRET_KEY = _required_secret('SECRET_KEY', lambda: get_random_secret_key())

# Encrypts stored API keys, SMTP passwords and OAuth tokens.
# Rotating this invalidates every stored credential; users must re-enter them.
FERNET_KEY = _required_secret('FERNET_KEY', lambda: Fernet.generate_key().decode())

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Public base URLs, used for OAuth redirects and unsubscribe links in outbound mail.
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# When true, sends with no connected mailbox are logged instead of delivered, and the
# response is explicitly flagged as sandboxed. Off by default: silently reporting
# success for undelivered mail is worse than failing.
ALLOW_SANDBOX_SEND = os.getenv('ALLOW_SANDBOX_SEND', 'False').lower() in ('1', 'true', 'yes')

# OAuth Credentials
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', 'DUMMY_GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', 'DUMMY_SECRET')
MICROSOFT_CLIENT_ID = os.getenv('MICROSOFT_CLIENT_ID', 'DUMMY_MS_CLIENT_ID')
MICROSOFT_CLIENT_SECRET = os.getenv('MICROSOFT_CLIENT_SECRET', 'DUMMY_SECRET')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Local apps
    'users',
    'leads',
    'integrations',
    'ai_engine',
    'inbox',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Deny by default. Without this DRF falls back to AllowAny, so any view that
    # forgets @permission_classes is world-readable.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '2000/day',
        'login': '10/min',      # brute-force guard on token issuance
        'ai': '60/hour',        # each call spends the tenant's LLM quota
        'send': '300/hour',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'richlead_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'richlead_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _postgres_database_config(database_url, sslmode='require'):
    parsed_database = urlsplit(database_url)
    if parsed_database.scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured('DATABASE_URL must use the PostgreSQL scheme.')
    if not parsed_database.hostname or not parsed_database.path.strip('/'):
        raise ImproperlyConfigured('DATABASE_URL must include a PostgreSQL hostname and database name.')
    database_options = {'sslmode': sslmode, 'connect_timeout': 10}
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed_database.path.lstrip('/')),
        'USER': unquote(parsed_database.username or ''),
        'PASSWORD': unquote(parsed_database.password or ''),
        'HOST': parsed_database.hostname or '',
        'PORT': parsed_database.port or 5432,
        'OPTIONS': database_options,
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }


DATABASE_URL = os.getenv('DATABASE_URL', '')
if DATABASE_URL:
    DATABASES = {'default': _postgres_database_config(DATABASE_URL, os.getenv('DATABASE_SSLMODE', 'require'))}
else:
    if not DEBUG:
        raise ImproperlyConfigured('DATABASE_URL must point to PostgreSQL whenever DEBUG is False.')
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Transport hardening. Inert under DEBUG so local http development still works.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'DENY'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# MAILERS is the Django 6.1+ replacement for EMAIL_BACKEND (which is removed in 7.0).
# Outreach mail goes out via SMTP/Gmail/Graph in integrations.services, not through this;
# this only covers Django-generated mail (password resets, admin error reports).
MAILERS = {
    'default': {
        'BACKEND': os.getenv(
            'EMAIL_BACKEND',
            'django.core.mail.backends.console.EmailBackend' if DEBUG
            else 'django.core.mail.backends.smtp.EmailBackend',
        ),
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '[{levelname}] {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'integrations': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'inbox': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
        'ai_engine': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
    },
}


from datetime import timedelta

SIMPLE_JWT = {
    # Access tokens are bearer secrets that cannot be revoked before they expire,
    # so they must be short. Revocation happens at the refresh layer instead.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}
