# Generated by Django 6.1.1 on 2026-09-26 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
        ('integrations', '0003_emailaccount_encrypted_imap_password_and_more'),
        ('leads', '0004_lead_title_alter_lead_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', '-received_at'], name='inbox_email_user_id_55f4a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(fields=('user', 'message_id'), name='uniq_message_per_user'),
        ),
    ]
