# Generated by Django 6.1.1 on 2026-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_emailmessage_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='rfc_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
