# Generated by Django 6.1.1 on 2026-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_existing_replies_read_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='intent',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not interested'), ('not_now', 'Not right now'), ('unsubscribe', 'Unsubscribe request'), ('out_of_office', 'Out of office / auto-reply'), ('referral', 'Referred to someone else'), ('question', 'Question'), ('other', 'Other')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='intent_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
