# Generated by Django 6.1.1 on 2026-09-26 09:34

from django.conf import settings
from django.db import migrations, models


def keep_one_active_template(apps, schema_editor):
    """Demote extra active templates before the partial-unique constraint lands.

    Nothing previously stopped a user having several active at once, and
    `.first()` picked an arbitrary one. Keep the most recently updated.
    """
    PromptTemplate = apps.get_model('ai_engine', 'PromptTemplate')
    seen = set()
    for template in PromptTemplate.objects.filter(is_active=True).order_by('-updated_at', '-id'):
        if template.user_id in seen:
            template.is_active = False
            template.save(update_fields=['is_active'])
        else:
            seen.add(template.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='avoid_topics',
            field=models.CharField(blank=True, default='', help_text='Anything the email must never mention.', max_length=300),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='call_to_action',
            field=models.CharField(blank=True, default='Ask if the problem is worth a short conversation. Do not ask for a meeting or send a link.', max_length=200),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='proof_point',
            field=models.CharField(blank=True, default='', help_text="One concrete, checkable result, e.g. 'took Loop from 4% to 11% reply rate in 6 weeks'.", max_length=300),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='sender_role',
            field=models.CharField(blank=True, default='', help_text="Who the email is from, e.g. 'Founder at Acme, a deliverability tool for B2B teams'.", max_length=150),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='value_proposition',
            field=models.TextField(blank=True, default='', help_text='What you actually do for customers, in one or two plain sentences.'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='system_prompt',
            field=models.TextField(default='You are an experienced SDR writing a first-touch cold email. Identify the single most likely problem this prospect has right now, then open with it. Earn a reply, not a meeting.'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='tone_of_voice',
            field=models.CharField(choices=[('Direct and professional', 'Direct and professional'), ('Warm and conversational', 'Warm and conversational'), ('Blunt and to the point', 'Blunt and to the point'), ('Curious and consultative', 'Curious and consultative')], default='Direct and professional', max_length=50),
        ),
        migrations.RunPython(keep_one_active_template, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_prompt_per_user'),
        ),
    ]
