# Generated by Django 6.1.1 on 2026-09-27 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_prompttemplate_avoid_topics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=300)),
                ('industry', models.CharField(blank=True, default='', max_length=150)),
                ('what_you_do', models.TextField(blank=True, default='', help_text='Plain description of the product or service, as you would say it out loud.')),
                ('problem_you_solve', models.TextField(blank=True, default='', help_text="The problem customers hire you to fix. The email opens on the prospect's version of this.")),
                ('ideal_customer', models.TextField(blank=True, default='', help_text='Who this is for: company size, role, industry.')),
                ('differentiator', models.TextField(blank=True, default='', help_text='Why you rather than the obvious alternative.')),
                ('proof_points', models.TextField(blank=True, default='', help_text='Concrete, checkable results. One per line.')),
                ('case_study', models.TextField(blank=True, default='', help_text='A named customer story the model may reference when it fits.')),
                ('never_claim', models.TextField(blank=True, default='', help_text='Claims the model must never make, e.g. compliance certifications you do not hold.')),
                ('sender_name', models.CharField(blank=True, default='', max_length=150)),
                ('sender_title', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('total_follow_ups', models.PositiveIntegerField(default=2, help_text='Follow-ups after the first email. 0 means send once and stop.')),
                ('days_between', models.PositiveIntegerField(default=4, help_text='Days to wait between touches.')),
                ('stop_on_reply', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
