# Generated by Django 6.1.1 on 2026-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_businessprofile_followupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='icp_employee_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='icp_employee_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='icp_industries',
            field=models.JSONField(blank=True, default=list, help_text="Target industry keywords, e.g. ['saas', 'software', 'fintech']."),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='icp_locations',
            field=models.JSONField(blank=True, default=list, help_text="Target location keywords, e.g. ['united states', 'uk', 'london']."),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='icp_requires_funding',
            field=models.BooleanField(default=False, help_text='Give fit weight to prospects with known funding (a proxy for budget).'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='icp_titles',
            field=models.JSONField(blank=True, default=list, help_text="Target job-title keywords, e.g. ['head of sales', 'sdr manager', 'vp sales']."),
        ),
    ]
