# Generated by Django 6.1.1 on 2026-10-05 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_businessprofile_icp_employee_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off', 'Off'), ('running', 'Running'), ('decided', 'Decided')], default='off', max_length=10)),
                ('variant_a_label', models.CharField(default='Question style', max_length=80)),
                ('variant_a_instruction', models.TextField(default='Write the subject as a short, specific question about their work.')),
                ('variant_b_label', models.CharField(default='Pain-point style', max_length=80)),
                ('variant_b_instruction', models.TextField(default='Write the subject as a plain statement naming the problem you solve for them.')),
                ('winner', models.CharField(blank=True, default='', max_length=1)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_experiment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
