# Generated by Django 6.1.1 on 2026-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reached', 'Reached Out'), ('replied', 'Replied'), ('blacklisted', 'Blacklisted')], default='pending', max_length=20),
        ),
    ]
