# Generated by Django 6.1.1 on 2026-09-26 00:49

from django.conf import settings
from django.db import migrations, models


def normalise_and_dedupe_emails(apps, schema_editor):
    """Lowercase every lead email, then drop per-user collisions the lowercasing creates.

    Runs before uniq_lead_email_per_user is applied. Keeps the oldest row for each
    (user, email) pair so the earliest outreach history survives.
    """
    Lead = apps.get_model('leads', 'Lead')
    for lead in Lead.objects.all().iterator():
        normalised = (lead.email or '').strip().lower()
        if normalised != lead.email:
            lead.email = normalised
            lead.save(update_fields=['email'])

    seen = set()
    for lead in Lead.objects.all().order_by('id').iterator():
        key = (lead.user_id, lead.email)
        if key in seen:
            lead.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RunPython(normalise_and_dedupe_emails, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'status'], name='leads_lead_user_id_8f1913_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='uniq_lead_email_per_user'),
        ),
    ]
