# Generated by Django 6.1.1 on 2026-09-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_title_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
