# Generated by Django 6.1.1 on 2026-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_backfill_send_reply_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesearch',
            name='generated_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='airesearch',
            name='pain_point',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='airesearch',
            name='spam_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='airesearch',
            name='spam_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesearch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
