# Generated by Django 6.1.1 on 2026-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='subject_variant',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1),
        ),
    ]
