# Generated by Django 6.1.1 on 2026-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_subject_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
