# Generated by Django 6.1.1 on 2026-09-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autopilot_active',
            field=models.BooleanField(default=False, help_text='If true, AI emails are sent automatically without manual review.'),
        ),
    ]
