# Generated by Django 6.1.1 on 2026-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_autopilot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unsubscribe_mode',
            field=models.CharField(choices=[('text', 'Plain-text line in the body (best for Primary tab)'), ('header', 'List-Unsubscribe header only (required for bulk senders)'), ('both', 'Both')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='unsubscribe_text',
            field=models.CharField(default="If you'd rather not hear from me, just reply with 'no thanks' and I'll leave you alone.", max_length=200),
        ),
    ]
